### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by platinummonkey** [platinummonkey/nginx-jwt#5]
Right now it's a wall of text. Let's make this more readable and consumable, perhaps using the github pages (or wiki) functionality of github.

**Comment by platinummonkey** [comment]
Also should provide better instructions on:
- how to setup dev environment
- how to start helping out. Including looking for the _want to start helping_ label
- how to contribute
- how to make your own api gateway + docker container tutorial example

**Comment by roryrjb** [comment]
@platinummonkey sounds good to me.

**Comment by platinummonkey** [comment]
Started down the github pages path: http://platinummonkey.github.io/nginx-jwt, just used the automatic page generator, needs some love.
